project:
  type: book

book:
  title: "Bioinfo Roadmap {{< fa computer>}}"
  author: "Marcel Ferreria"
  page-footer:
    border: true
    left: "Marcel Ferreira \\@marceelrf"
  date: today
  chapters:
    - index.qmd
    - part: bioinfobasis_part.qmd
    - part: linuxfoundations_part.qmd
    - part: "R programming basis"
      chapters:
      - rpart01.qmd
    - part: pythonbasis_part.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

